error: fix handling of boomError to ensure they're serialized as json properly
without the deep merge, the `content-type: application/json` header set
by the json helper gets clobbered b/c boom errors have output.headers
set (to an empty object by default)

fleshed out tests related to boom errors thrown by paperplane to ensure
the response body is set correctly as well (these tests fail without the
change in lib/error.js)